import type { Content } from '../engine/model.js';
import { score } from '../engine/score.js';
import { decodeState, type DecodeError } from '../state/encode.js';
import {
  Alternatives,
  Assumptions,
  NextStep,
  ProsCons,
  RecommendationCard,
  ScenarioSummary,
  WhyNot,
  indexApproaches,
} from './result-parts.js';

const DECODE_MESSAGE: Record<DecodeError, string> = {
  empty: 'This link has no answers in it.',
  malformed: 'This link is malformed and could not be read.',
  'unknown-schema': 'This link was made by an incompatible version of the tool.',
  'version-mismatch':
    'This link was made against a different version of the recommendation rules, so it can no longer be shown accurately. Please re-run the questionnaire.',
  'length-mismatch': 'This link does not match the current questionnaire.',
  'option-out-of-range': 'This link refers to an answer that no longer exists.',
};

/**
 * The `?view=export&state=…` print one-pager. It re-runs the SAME scoring
 * engine over the decoded answers — nothing is trusted from the URL except the
 * option choices, and those are validated against the current content version
 * before use (defensive decode; reject unknown versions — eng review Issues 3 + 8).
 *
 * Print-first: the screen shows a warning banner + a Print button; the printed
 * page (browser "Save as PDF") is the deliverable, stamped with the content
 * version and last-reviewed date.
 */
export function ExportView({ content, state }: { content: Content; state: string | null }) {
  const decoded = decodeState(state, content);

  if (!decoded.ok) {
    return (
      <main className="export export--error">
        <h1>Cannot open this one-pager</h1>
        <p>{DECODE_MESSAGE[decoded.reason]}</p>
        <p className="no-print">
          <a className="btn btn--primary" href={base()}>
            Start the questionnaire
          </a>
        </p>
      </main>
    );
  }

  const answers = decoded.answers;
  const result = score(answers, content);
  const approaches = indexApproaches(content);

  return (
    <main className="export">
      <div className="export__warning no-print" role="note">
        <strong>Heads up:</strong> this link encodes the answers you selected. Anyone you
        share it with will see the same scenario and recommendation.
      </div>

      <div className="export__actions no-print">
        <button type="button" className="btn btn--primary" onClick={() => window.print()}>
          Print / Save as PDF
        </button>
        <a className="btn btn--ghost" href={base()}>
          Back to questionnaire
        </a>
      </div>

      <article className="onepager">
        <header className="onepager__head">
          <h1 className="onepager__title">Agent approach recommendation</h1>
          <p className="onepager__stamp">
            Rules version {content.version} · last reviewed {content.lastReviewed}
          </p>
        </header>

        <ScenarioSummary content={content} answers={answers} />
        <RecommendationCard result={result} approaches={approaches} />
        <Alternatives result={result} />
        <ProsCons result={result} approaches={approaches} />
        <WhyNot result={result} approaches={approaches} />
        <Assumptions result={result} />
        <NextStep result={result} />

        <footer className="onepager__foot">
          <p>
            Generated by the Agent Adoption Advisor. This is a decision aid, not a Microsoft
            commitment. Confirm product specifics with your account team.
          </p>
        </footer>
      </article>
    </main>
  );
}

/** URL to the questionnaire (drops query + hash), robust under a sub-path deploy. */
function base(): string {
  if (typeof window === 'undefined') return '/';
  return window.location.pathname;
}
